apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: default
  labels:
    app: redpanda
    managed-by: endfield
spec:
  serviceName: redpanda-headless
  replicas: 2
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:v23.3.11
          ports:
            - containerPort: 9092