apiVersion: v2
name: prometheus
description: Endfield managed Helm release for prometheus
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "58.2.2"
    repository: "https://prometheus-community.github.io/helm-charts"
