apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom
  namespace: default
  labels:
    app: custom
    managed-by: endfield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
        - name: custom
          image: 
          ports:
            - containerPort: 8080