apiVersion: v1
kind: Service
metadata:
  name: kafkaasdadads
  namespace: test3
  labels:
    app: kafkaasdadads
    managed-by: endfield
spec:
  type: ClusterIP
  selector:
    app: kafkaasdadads
  ports:
    - name: main
      port: 9092
      targetPort: 9092
      protocol: TCP
