apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: test3
  labels:
    app: postgres
    managed-by: endfield
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
