apiVersion: v1
kind: Service
metadata:
  name: postgres123-headless
  namespace: test3
  labels:
    app: postgres123
    managed-by: endfield
spec:
  clusterIP: None
  selector:
    app: postgres123
  ports:
    - name: main
      port: 5432
      targetPort: 5432
