apiVersion: v1
kind: Service
metadata:
  name: postgresdsfsdfsdf-headless
  namespace: test3
  labels:
    app: postgresdsfsdfsdf
spec:
  clusterIP: None
  selector:
    app: postgresdsfsdfsdf
  ports:
    - port: 5432
      targetPort: 5432
