apiVersion: v1
kind: Service
metadata:
  name: postgres123
  namespace: test3
  labels:
    app: postgres123
    managed-by: endfield
spec:
  type: ClusterIP
  selector:
    app: postgres123
  ports:
    - name: main
      port: 5432
      targetPort: 5432
      protocol: TCP
