apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres123-config
  namespace: test3
  labels:
    app: postgres123
    managed-by: endfield
data:
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "postgres"
