apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresasdf-config
  namespace: default
  labels:
    app: postgresasdf
    managed-by: endfield
data:
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "postgres"
