apiVersion: v1
kind: Secret
metadata:
  name: postgresasdf-secret
  namespace: default
  labels:
    app: postgresasdf
    managed-by: endfield
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme"
