apiVersion: v1
kind: Service
metadata:
  name: postgresasdf
  namespace: default
  labels:
    app: postgresasdf
    managed-by: endfield
spec:
  type: ClusterIP
  selector:
    app: postgresasdf
  ports:
    - name: main
      port: 5432
      targetPort: 5432
      protocol: TCP
