apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: default
  labels:
    app: postgres
    managed-by: endfield
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: main
      port: 5432
      targetPort: 5432
