apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx
  namespace: default
  labels:
    app: ingress-nginx
    managed-by: endfield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
        - name: ingress-nginx
          image: registry.k8s.io/ingress-nginx/controller:v1.9.6
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
