apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: default
  labels:
    app: ingress-nginx
    managed-by: endfield
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
    - name: main
      port: 80
      targetPort: 80
      protocol: TCP
