apiVersion: v2
name: ingress-nginxjhh
description: Endfield-managed wrapper chart for ingress-nginxjhh
type: application
version: 0.1.0
appVersion: ""

dependencies:
  - name: ingress-nginx
    version: "4.10.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
