# Production overrides — edit this file for prod deployments
ingress-nginx:
  controller:
    replicaCount: 2

    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

    admissionWebhooks:
      enabled: true
