ingress-nginx:
  namespaceOverride: "infra-ingress-nginx"

  controller:
    replicaCount: 1

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    service:
      type: LoadBalancer
      annotations: {}

    ingressClassResource:
      name: nginx
      enabled: true
      default: false

    admissionWebhooks:
      enabled: false

  rbac:
    create: true
