redis:
  namespaceOverride: "infra-redis"

  architecture: standalone

  auth:
    enabled: false
    # Set to true and provide password for production
    # password: ""

  master:
    persistence:
      enabled: true
      size: 2Gi

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  replica:
    replicaCount: 0
